# Data
#path: /content/gdrive/MyDrive/AI-pose
#train: images/train  # train images (relative to 'path')
#val: images/val  # val images (relative to 'path')

path: C:\PyCharm_project_final_year\Yolov8_yoga_pose\data_folder\images
train: train
val: valid

# Keypoints
kpt_shape: [17, 3]  # [number of keypoints, number of dim]
flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]

# Classes
names:
  0: Anjaneyasana
  1: katichakrasana
  2: padmasana
  3: trikonasana
  4: vrkasana